### PR TITLE
Add evaluation graph

### PR DESCRIPTION
**Pull request by pwindle**
Adds evaluation graph with classification icons on hover.

https://github.com/WintrCat/freechess/assets/28284434/c22eb288-72d2-45d6-b42a-01c1388eecac

### CODE REVIEW

**Comment by dan-supetree** [comment]
wow! this is great

**Comment by leye195** [comment]
wow:)  this is great! 👍

**Comment by Kinggodhoon** [comment]
i love it,
i think change mouse cursor when hover the mouse on graph it will be more awesome

**Comment by pwindle** [comment]
@Kinggodhoon That could be good. Like a crosshair perhaps? 

Might also put the classification icon in a speech bubble type box with player name, and evaluation score.

Another thing which chess.com does now is keeps the dots for blunders, mistakes, bests, and brilliants always visible. Do we want it to be more like that?

**Comment by pwindle** [comment]
Added custom cursor, info boxes, player names on hover. Better, or maybe too much?

https://github.com/WintrCat/freechess/assets/28284434/5cbd3b19-3ea7-4945-9bbd-8af3b09de333

**Comment by WintrCat** [comment]
This is great, thank you @pwindle 👍 
Cursor and info boxes look fine

**Pull request merged**
